ImportExport/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('<str:format>/', views.export, name='export'),
    path('', views.MainView.as_view()),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=450)
    liked = models.ManyToManyField(User, related_name='liked')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Post {self.pk}'

    @property
    def comments(self):
        return self.comment_set.all()



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment {self.pk}'

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .admin import PostResource
from django.http import HttpResponse


class MainView(TemplateView):
    template_name = 'core/home.html'


def export(request, format):
    posts_resource = PostResource()
    dataset = posts_resource.export()
    if format == 'csv':
        dataset_format = dataset.csv
    else:
        dataset_format = dataset.xls
    response = HttpResponse(dataset_format, content_type=f'text/{format}')
    response['Content-Disposition'] = f"attachment; filename=posts.{format}"
    return response

templates/core/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Import/Export</title>
</head>

<body>
    
    <div class="container mt-3">
        {% block content %}
        
        {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/core/home.html
{% extends 'core/base.html' %}
{% block content %}
    <h3>Export Data</h3>
    <hr>
    <a href="{% url 'posts:export' 'xls' %}" class="btn btn-success">xls</a>
    <a href="{% url 'posts:export' 'csv' %}" class="btn btn-warning">csv</a>
{% endblock %}